config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'menus#index'
  resources :recipes
  resources :menus do
    collection do
      get 'sort'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook_time.rb
class CookTime < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ーー'},
    { id: 2, name: '10分以内'},
    { id: 3, name: '20分程度'},
    { id: 4, name: '30分程度'},
    { id: 5, name: '40分以上'}
  ]

  include ActiveHash::Associations
  has_many :recipes

end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ーー'},
    { id: 2, name: '和食'},
    { id: 3, name: '中華'},
    { id: 4, name: '洋食'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :recipes

end

app/models/menu.rb
class Menu < ApplicationRecord

  def start_time
    self.cook_date
  end

  has_many :menus_recipes
  has_many :recipes, through: :menus_recipes


  with_options presence:{ message: 'を選択してください'}  do
   validates :main
  end

end

app/models/menus_recipe.rb
class MenusRecipe < ApplicationRecord
  belongs_to :menu
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre, :cook_time, :side_dishes

  has_many :menus_recipes
  has_many :menus, through: :menus_recipes
  has_one_attached :image

  validates :image, presence: { message: 'を選択してください' }
  with_options presence: true do
  validates :cooking_name, :ingredient, :process, :user_id
    with_options numericality: { other_than: 1, message: 'を選択してください' } do
      validates :genre_id, :cook_time_id, :side_dishes_id
    end
  end
end

app/models/side_dishes.rb
class SideDishes < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ーー'},
    { id: 2, name: '主菜'},
    { id: 3, name: '副菜'},
    { id: 4, name: '汁物'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :recipes

end

app/models/user.rb
class User < ApplicationRecord
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = 'gestpass'
      user.name = 'ゲスト'
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :access_check, only:[:edit, :update]

  def index
      @menus = Menu.where(user_id: current_user.id)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(cook_date_params)
    create_menu
    if @menu.save
      redirect_to root_path
    else
      flash[:notice] = "料理が選択されていません"
      redirect_to new_menu_path
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to root_path
  end

  def sort
    @recipe = Recipe.where(genre_id: params[:genre]).where(side_dishes_id: params[:sidedishes])
    render :sort
  end

  private
  
  def cook_date_params
  params.require(:menu).permit(:cook_date, recipe_ids:[]).merge(user_id: current_user.id)
  end

  def create_menu
    dish = @menu.recipe_ids
    main_name = Recipe.where(id: dish.first).pluck(:cooking_name)
    @menu[:main] = main_name[0]
    sub_one_name = Recipe.where(id: dish.second).pluck(:cooking_name)
    @menu[:sub_one] = sub_one_name[0]
    sub_two_name = Recipe.where(id: dish.third).pluck(:cooking_name)
    @menu[:sub_two] = sub_two_name[0]
    soup_name = Recipe.where(id: dish.fourth).pluck(:cooking_name)
    @menu[:soup] = soup_name[0]
  end

  def access_check
    author = Recipe.find(params[:id])
    if current_user.id != author.user_id
      redirect_to root_path
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,  except:[:show]
  before_action :access_check, only:[:edit, :update]

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id)
    else
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:image, :cooking_name, :ingredient, :process, :genre_id, :cook_time_id, :side_dishes_id).merge(user_id: current_user.id )
  end

  def access_check
    author = Recipe.find(params[:id])
    if current_user.id != author.user_id
      redirect_to root_path
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kondate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </body>
</html>

app/views/menus/index.html.erb
<%= render  "shared/header" %>

<div class="main">
  <div class="menu-recipe">
    <div class="menu-make"><%= link_to '献立を立てる', new_menu_path, class: "menu" %></div>
    <div class="recipe-make"><%= link_to 'レシピを投稿する', new_recipe_path, class: "recipe" %></div>
    <div class="my-recipe"><%= link_to '投稿したレシピ一覧', recipes_path(current_user.id), class: "myrecipe" %></div>
  </div>

  <div class="calendar-name">
    <h1>献立カレンダー</h2>
  </div>

  <div class="calendar">
  <%= month_calendar events: @menus do |date, all| %>
    <%= date.day %>
    <% all.each do |i| %>
      <div>
        <div class="delete-btn">
          <%= link_to '献立を削除', menu_path(i.id), method: :delete, class: "menu-delete" %>
        </div>
        <ul class="menu-day">
          <% menu = i.menus_recipes %>
          <% menu.each do |n| %>
            <% name = Recipe.find(n.recipe_id) %>
            <li><%= link_to name.cooking_name, recipe_path(name.id), class: "cook-name" %></li>
          <% end %> 
        </ul>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

<%= render  "shared/footer" %>

app/views/menus/new.html.erb
<div id="modal-overlay">
  <div id="modal-content">
    <p>写真をクリックして献立に追加する料理を選択してください</p>
    <div id="menu-list"></div>
    <p><a id="modal-close" class="button-link">閉じる</a></p>
  </div>
</div>

<%= render "shared/header" %>

<div class="menu-new-content">
<%= form_with(model: @menu, local: true) do |form| %>

  <div id="hide-input"></div>

  <div class="menu-make-form">
    <%# <div class="menu-input">
      <%= form.label :献立をつくろう %>
    <%#</div> %>

    <%= render "shared/error_message", model: form.object %>
    <% if flash[:notice] == "料理が選択されていません" %>
    <div class="error-text">
    <%= flash[:notice] %>
    </div>
    <% end %>

      <div class="menu-input">
        <p>献立を立てる日付を決めよう</p>
        <%= form.date_select :cook_date %>
      </div>

      <div id="menu-palette"></div>

      <div id="menu-form" class="menu-none">
        <select name="genre" id="genre" class="select-box">
          <option disabled selected>料理のジャンルは？</option>
          <option value="2">和食</option>
          <option value="3">中華</option>
          <option value="4">洋食</option>
          <option value="5">その他</option>
        </select>

        <select name="side-dishes" id="side-dishes" class="select-box">
          <option disabled selected>おかずの種類は？</option>
          <option value="2">主菜</option>
          <option value="3">副菜</option>
          <option value="4">汁物</option>
          <option value="5">その他</option>
        </select>
      </div>

      <div class="sort-btn" id="sort">料理を検索</div>
      <div class="submit" ><%= form.submit "献立を確定する", class: "menu-make-btn"%></div>
  </div>
<% end %>

  <div class="lecture-contents">
    <div class="lecture-title-box">
      <div class="lecture-title">
        アプリ「kondate」で献立を作成する方法
      </div>
    </div>
    <div class="lecture-content">
      <div class="lecture-text">
        1.料理のジャンル、おかずの種類を選択し、「料理を検索」
      </div>
      <div class="lecture-img">
        <%= image_tag 'lecture1.png', width: '100%', height: '100%' %>
      </div>
    </div>
    <div class="lecture-content">
      <div class="lecture-text">
        2.表示される料理を選択
      </div>
      <div class="lecture-img">
        <%= image_tag 'lecture2.jpg', width: '100%', height: '100%' %>
      </div>
    </div>
    <div class="lecture-content">
      <div class="lecture-text">
        3.選択した料理が右の画像のように表示されます
      </div>
      <div class="lecture-img">
        <%= image_tag 'lecture3.png', width: '100%', height: '100%' %>
      </div>
    </div>
    <div class="lecture-content">
      <div class="lecture-text">
        4.①〜③を繰り返し、好みの献立を作り「献立を確定する」をクリック。
          マイページのカレンダーに作成した献立が登録されます。<br>
          ※現状、1度に追加できる料理の数は4つまでとなっています。
      </div>
      <div class="lecture-img">
        <%= image_tag 'lecture4.jpg', width: '100%', height: '100%' %>
      </div>
    </div>
  </div>

</div>

<%= render  "shared/footer" %>

app/views/recipes/edit.html.erb
<%= render  "shared/header" %>
<div class="content">
  <div class="form-title">
    <h1>レシピ編集フォーム</h1>
  </div>
  <%= render "shared/form" %> 
</div>
<%= render  "shared/footer" %>

app/views/recipes/index.html.erb
<%= render  "shared/header" %>
<div class="my-recipe-content">
  <div class="my-recipe-title">投稿したレシピ一覧</div>
    <div class="my-recipe-warper">
      <% @recipes.each do |recipe| %>
      <div class="my-recipe-data">
        <div><%= link_to recipe.cooking_name, recipe_path(recipe.id), class: "myrecipe-menuname" %></div>
        <div><%= image_tag(recipe.image.variant(resize:"300x200")) %></div>
      </div>
      <% end %>
    </div>
</div>
<%= render  "shared/footer" %>

app/views/recipes/new.html.erb
<%= render  "shared/header" %>
<div class="content">
  <div class="form-title">
    <h1>レシピ投稿フォーム</h1>
  </div>
  <%= render "shared/form" %> 
</div>
<%= render  "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>
  <div class="edit-content">
    <div class="edit-box">
      <% if user_signed_in? %>
        <div class="recipe-edit-btn">
          <%= link_to 'レシピの編集', edit_recipe_path(@recipe.id), style: "text-decoration:none;" %>
        </div>
      <% end %>
    </div>
    <div class="edit-text">
      <div class="edit-form edit-name">
        <h1><%= @recipe.cooking_name %></h1>
      </div>
      <div class="edit-img"> 
        <%= image_tag @recipe.image.variant(resize: '500x500')  if @recipe.image.attached? %>
      </div>
      <div class="edit-form edit-ingredient">
        <h2>材料・調味料</h2>
      </div>
      <div class="edit-from edit-ingredient-text">
        <%= safe_join(@recipe.ingredient.split("\n"),tag(:br)) %>
      </div>
      <div class="edit-form show-process">
        <h2>作り方</h2>
      </div>
      <div class="edit-form show-process-text">
        <%= safe_join(@recipe.process.split("\n"),tag(:br)) %>
      </div>  
    </div>
  </div>
<%= render  "shared/footer" %>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <% if message = "メインを選択してください"%>
        <li class='error-message'>料理が選択されていません</li>
        <% else %>
        <li class='error-message'><%= message %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="footer-list">
    <li><%= link_to 'カレンダー', root_path, class: "link-name" %></li>
    <li>/</li>
    <li><%= link_to '献立を立てる', new_menu_path, class: "link-name" %></li>
    <li>/</li>
    <li><%= link_to 'レシピ投稿', new_recipe_path, class: "link-name" %></li>
  </ul>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @recipe, local: true do |f| %>
<%= render "shared/error_message", model: f.object %>

  <table class="cook-form">
    <tbody>
      <tr>
        <th>料理名</th>
        <td><%= f.text_field :cooking_name, style: "border:none" %></td>
      </tr>
      <tr>
        <th>写真</th>
        <td><%= f.file_field :image %></td>
      </tr>
      <tr>
        <th>必要な材料・調味料</th>
        <td><%= f.text_area :ingredient, style: "border:none" %></td>
      </tr>
      <tr>
        <th>作り方</th>
        <td><%= f.text_area :process, style: "border:none" %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, {} ) %></td>
      </tr>
      <tr>
        <th>調理時間</th>
        <td><%= f.collection_select(:cook_time_id, CookTime.all, :id, :name, {} )%></td>
      </tr>
      <tr>
        <th>おかずの種類</th>
        <td><%= f.collection_select(:side_dishes_id, SideDishes.all, :id, :name, {} )%></td>
      </tr>
    </tbody>
  </table>
  <div class="form-btn">
  <%= f.submit "レシピを投稿する" %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="app-name"><%= link_to (image_tag "logo.png"), "/" %></div>

    <ul class="head-user">
    <% if user_signed_in? %>
      <div class="user-box">
        <li><%= link_to "こんにちは、#{current_user.name}さん", root_path, class: "left-box" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "right-box" %></li>
      </div>
    <% else %>
      <div class="not-user-box">
        <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "login-box" %></li>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login-box" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-in-box" %></li>
      </div>
    <% end %>
    <ul> 
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead class="table-head">
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>